import KoboldCpp from './Koboldcpp';
import createClient from 'openapi-fetch';
import type { paths } from './generated/koboldCppDefinition'; // generated by openapi-typescript

const KoboldCppDirectClient = (args: Parameters<typeof createClient<paths>>) =>
	createClient<paths>(...args);

export default KoboldCpp;
export { KoboldCppDirectClient };
